# Generated by Django 3.1.4 on 2021-03-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
