# Generated by Django 3.1.4 on 2021-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_auto_20210314_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
