# Generated by Django 3.1.4 on 2021-03-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0006_remove_image_resolutin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='resolutin',
            new_name='resolution',
        ),
    ]
